/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crud.sederhana;

public class App {
    public static void main(String[] args) {
        new MainApp().setVisible(true);
    }
}
